image: maven:3-jdk-11

# Maven configuration from https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  # `-s makes make use repository-local settings that include proxy config`
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s $CI_PROJECT_DIR/ci_settings.xml"
  HTTP_PROXY: "http://proxy.univ-lyon1.fr:3128"
  http_proxy: "http://proxy.univ-lyon1.fr:3128"
  HTTPS_PROXY: "http://proxy.univ-lyon1.fr:3128"
  https_proxy: "http://proxy.univ-lyon1.fr:3128"
  NO_PROXY: "localhost,127.0.0.1,forge.univ-lyon1.fr,docker"


# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - build
  - test

package:
  stage: build
  script:
    - cd root; mvn jetty:run; mvn $MAVEN_CLI_OPTS package

test-maintenance-api:
  stage: test
  script:
    - cd root/maintenance-web
    - mvn $MAVEN_CLI_OPTS jetty:run 2>&1 > maintenance.jetty.log & mvn_jetty_pid=$!
    # wait for jetty to be ready for fail after 45s
    - for i in $(seq 10); do grep -q "Started Jetty Server" maintenance.jetty.log && break; [ $i = 10 ] && echo "Jetty failed to start" && cat maintenance.jetty.log && exit 1; echo "Jetty not ready, waiting 5s"; sleep 5; done
    - mvn $MAVEN_CLI_OPTS jmeter:jmeter jmeter:results || (kill $mvn_jetty_pid; exit 1)
    - kill $mvn_jetty_pid
