# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
#spring.main.allow-bean-definition-overriding=true
server.port=9000

spring.main.allow-bean-definition-overriding=true

keycloak.auth-server-url=http://localhost:8180/auth/
keycloak.realm=SpringBootKeycloak
keycloak.resource=login-app
keycloak.public-client=true
keycloak.principal-attribute=preferred_username

keycloak.security-constraints[0].authRoles[0]=admin
keycloak.security-constraints[0].securityCollections[0].patterns[0]=/trottinette/add
keycloak.security-constraints[0].securityCollections[0].patterns[1]=/trottinette/delete/*
keycloak.security-constraints[0].securityCollections[0].patterns[2]=/abonne/*
keycloak.security-constraints[0].securityCollections[0].patterns[3]=/emprunt/*

rabbitmq.banque-queue=banque-queue
rabbitmq.emprunt-queue=emprunt-queue

spring.jackson.serialization.fail-on-empty-beans=false