# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
#spring.main.allow-bean-definition-overriding=true
server.port=9000

# keycloack username : lucas | mdp : p1408928
# keycloack username : user1 | mdp: user1Test